server:
    port: 8080

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://ep-raspy-morning-ae21lxhy-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_g2PzDZye6jTc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

